### PR TITLE
DEV-11356 - Shared channel synchronization to handle concurrency

### PR DESCRIPTION
**Pull request by ElenaVolkova**
https://www.rabbitmq.com/api-guide.html
As a rule of thumb, sharing Channel instances between threads is something to be avoided. 
Concurrent publishing on a shared channel can result in incorrect frame interleaving on the wire, triggering a connection-level protocol exception and immediate connection closure by the broker. It therefore requires explicit synchronization in application code (Channel#basicPublish must be invoked in a critical section).

### CODE REVIEW

**Comment by ElenaVolkova** [comment]
> Can we have a version of publish that is not using lock?

Not in the current implementation. The channel is created manually, it should be a logic to manage channels. It is recommended to use Spring amqp library to do this job, but in the current implementation we can't easily move to the spring amqp.

**Comment by baot** [comment]
> > Can we have a version of publish that is not using lock?
> 
> Not in the current implementation. The channel is created manually, it should be a logic to manage channels. It is recommended to use Spring amqp library to do this job, but in the current implementation we can't easily move to the spring amqp.

I mean a optional publishWithoutLock like before when we use in single thread manner, so we don't have a lock.lock()  during publish call.

**Comment by ElenaVolkova** [comment]
> > > Can we have a version of publish that is not using lock?
> > 
> > 
> > Not in the current implementation. The channel is created manually, it should be a logic to manage channels. It is recommended to use Spring amqp library to do this job, but in the current implementation we can't easily move to the spring amqp.
> 
> I mean a optional publishWithoutLock like before when we use in single thread manner, so we don't have a lock.lock() during publish call.

Yes, understood your point. Will add publishWithLock method do not have changes in other services when they will be moving to the other JTL version

**Comment by ElenaVolkova** [comment]
> > > > Can we have a version of publish that is not using lock?
> > > 
> > > 
> > > Not in the current implementation. The channel is created manually, it should be a logic to manage channels. It is recommended to use Spring amqp library to do this job, but in the current implementation we can't easily move to the spring amqp.
> > 
> > 
> > I mean a optional publishWithoutLock like before when we use in single thread manner, so we don't have a lock.lock() during publish call.
> 
> Yes, understood your point. Will add publishWithLock method do not have changes in other services when they will be moving to the other JTL version

Apparently, we publish via the same connection from the different threads everywhere and we need to use lock. We can think about managing of the channels between threads to remove locks, but it should be a separate task.

**Pull request merged**
